import { readFile, writeFile } from "node:fs/promises"

import fontkit from "@pdf-lib/fontkit"

import { FONT_CUT_FILES } from "../src/domain/fonts.ts"

// Advance widths for every bundled static cut. `src/domain/text-layout.ts` uses
// them to break lines identically in the browser preview and the PDF renderer.
const generated = Object.fromEntries(
  await Promise.all(
    Object.entries(FONT_CUT_FILES).map(async ([cut, path]) => {
      const font = fontkit.create(await readFile(path))
      const advances: Record<number, number> = {}
      for (const codePoint of font.characterSet) {
        advances[codePoint] = font.glyphForCodePoint(codePoint).advanceWidth
      }
      return [
        cut,
        {
          unitsPerEm: font.unitsPerEm,
          fallbackAdvance: font.glyphForCodePoint(0).advanceWidth,
          advances,
        },
      ]
    })
  )
)

const output = `// Generated by scripts/generate-font-metrics.ts from the bundled print fonts.\nexport const FONT_METRICS = ${JSON.stringify(generated)} as const\n`
await writeFile("src/domain/font-metrics.generated.ts", output)
