import { readFile, writeFile } from "node:fs/promises"

import fontkit from "@pdf-lib/fontkit"

const fonts = [
  ["Inter-normal-normal", "assets/fonts/Inter-Regular.ttf"],
  ["Inter-normal-bold", "assets/fonts/Inter-Bold.ttf"],
  ["Inter-italic-normal", "assets/fonts/Inter-Italic.ttf"],
  ["Inter-italic-bold", "assets/fonts/Inter-BoldItalic.ttf"],
  ["Source Serif 4-normal-normal", "assets/fonts/SourceSerif4-Regular-Print.ttf"],
  ["Source Serif 4-normal-bold", "assets/fonts/SourceSerif4-Bold-Print.ttf"],
  ["Source Serif 4-italic-normal", "assets/fonts/SourceSerif4-Italic-Print.ttf"],
  ["Source Serif 4-italic-bold", "assets/fonts/SourceSerif4-BoldItalic-Print.ttf"],
] as const

const generated = Object.fromEntries(
  await Promise.all(
    fonts.map(async ([key, path]) => {
      const font = fontkit.create(await readFile(path))
      const advances: Record<number, number> = {}
      for (const range of font.characterSet) {
        advances[range] = font.glyphForCodePoint(range).advanceWidth
      }
      return [
        key,
        {
          unitsPerEm: font.unitsPerEm,
          fallbackAdvance: font.glyphForCodePoint(0).advanceWidth,
          advances,
        },
      ]
    })
  )
)

const output = `// Generated by scripts/generate-font-metrics.ts from the bundled print fonts.\nexport const FONT_METRICS = ${JSON.stringify(generated)} as const\n`
await writeFile("src/domain/font-metrics.generated.ts", output)
