/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutParityRouteImport } from './routes/layout-parity'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiProjectsRouteImport } from './routes/api.projects'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as ApiAssetsAssetIdRouteImport } from './routes/api.assets.$assetId'
import { Route as ApiExportsExportIdRouteImport } from './routes/api.exports.$exportId'
import { Route as ApiProjectsProjectIdRouteImport } from './routes/api.projects.$projectId'
import { Route as ApiShareTokenRouteImport } from './routes/api.share.$token'
import { Route as ApiProjectsProjectIdAssetsRouteImport } from './routes/api.projects.$projectId.assets'
import { Route as ApiProjectsProjectIdBookRouteImport } from './routes/api.projects.$projectId.book'
import { Route as ApiProjectsProjectIdCloseRouteImport } from './routes/api.projects.$projectId.close'
import { Route as ApiProjectsProjectIdDuplicateRouteImport } from './routes/api.projects.$projectId.duplicate'
import { Route as ApiProjectsProjectIdExportRouteImport } from './routes/api.projects.$projectId.export'
import { Route as ApiProjectsProjectIdLayoutsRouteImport } from './routes/api.projects.$projectId.layouts'
import { Route as ApiProjectsProjectIdPublishRouteImport } from './routes/api.projects.$projectId.publish'
import { Route as ApiProjectsProjectIdLayoutsLayoutIdRouteImport } from './routes/api.projects.$projectId.layouts.$layoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutParityRoute = LayoutParityRouteImport.update({
  id: '/layout-parity',
  path: '/layout-parity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsAssetIdRoute = ApiAssetsAssetIdRouteImport.update({
  id: '/api/assets/$assetId',
  path: '/api/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportsExportIdRoute = ApiExportsExportIdRouteImport.update({
  id: '/api/exports/$exportId',
  path: '/api/exports/$exportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdRoute = ApiProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiShareTokenRoute = ApiShareTokenRouteImport.update({
  id: '/api/share/$token',
  path: '/api/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdAssetsRoute =
  ApiProjectsProjectIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdBookRoute =
  ApiProjectsProjectIdBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdCloseRoute =
  ApiProjectsProjectIdCloseRouteImport.update({
    id: '/close',
    path: '/close',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdDuplicateRoute =
  ApiProjectsProjectIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdExportRoute =
  ApiProjectsProjectIdExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdLayoutsRoute =
  ApiProjectsProjectIdLayoutsRouteImport.update({
    id: '/layouts',
    path: '/layouts',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdPublishRoute =
  ApiProjectsProjectIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiProjectsProjectIdLayoutsLayoutIdRoute =
  ApiProjectsProjectIdLayoutsLayoutIdRouteImport.update({
    id: '/$layoutId',
    path: '/$layoutId',
    getParentRoute: () => ApiProjectsProjectIdLayoutsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/layout-parity': typeof LayoutParityRoute
  '/api/health': typeof ApiHealthRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/s/$token': typeof STokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/exports/$exportId': typeof ApiExportsExportIdRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/share/$token': typeof ApiShareTokenRoute
  '/api/projects/$projectId/assets': typeof ApiProjectsProjectIdAssetsRoute
  '/api/projects/$projectId/book': typeof ApiProjectsProjectIdBookRoute
  '/api/projects/$projectId/close': typeof ApiProjectsProjectIdCloseRoute
  '/api/projects/$projectId/duplicate': typeof ApiProjectsProjectIdDuplicateRoute
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
  '/api/projects/$projectId/layouts': typeof ApiProjectsProjectIdLayoutsRouteWithChildren
  '/api/projects/$projectId/publish': typeof ApiProjectsProjectIdPublishRoute
  '/api/projects/$projectId/layouts/$layoutId': typeof ApiProjectsProjectIdLayoutsLayoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/layout-parity': typeof LayoutParityRoute
  '/api/health': typeof ApiHealthRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/s/$token': typeof STokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/exports/$exportId': typeof ApiExportsExportIdRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/share/$token': typeof ApiShareTokenRoute
  '/api/projects/$projectId/assets': typeof ApiProjectsProjectIdAssetsRoute
  '/api/projects/$projectId/book': typeof ApiProjectsProjectIdBookRoute
  '/api/projects/$projectId/close': typeof ApiProjectsProjectIdCloseRoute
  '/api/projects/$projectId/duplicate': typeof ApiProjectsProjectIdDuplicateRoute
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
  '/api/projects/$projectId/layouts': typeof ApiProjectsProjectIdLayoutsRouteWithChildren
  '/api/projects/$projectId/publish': typeof ApiProjectsProjectIdPublishRoute
  '/api/projects/$projectId/layouts/$layoutId': typeof ApiProjectsProjectIdLayoutsLayoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/layout-parity': typeof LayoutParityRoute
  '/api/health': typeof ApiHealthRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/s/$token': typeof STokenRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/assets/$assetId': typeof ApiAssetsAssetIdRoute
  '/api/exports/$exportId': typeof ApiExportsExportIdRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/api/share/$token': typeof ApiShareTokenRoute
  '/api/projects/$projectId/assets': typeof ApiProjectsProjectIdAssetsRoute
  '/api/projects/$projectId/book': typeof ApiProjectsProjectIdBookRoute
  '/api/projects/$projectId/close': typeof ApiProjectsProjectIdCloseRoute
  '/api/projects/$projectId/duplicate': typeof ApiProjectsProjectIdDuplicateRoute
  '/api/projects/$projectId/export': typeof ApiProjectsProjectIdExportRoute
  '/api/projects/$projectId/layouts': typeof ApiProjectsProjectIdLayoutsRouteWithChildren
  '/api/projects/$projectId/publish': typeof ApiProjectsProjectIdPublishRoute
  '/api/projects/$projectId/layouts/$layoutId': typeof ApiProjectsProjectIdLayoutsLayoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/layout-parity'
    | '/api/health'
    | '/api/projects'
    | '/projects/$projectId'
    | '/s/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/projects/'
    | '/api/assets/$assetId'
    | '/api/exports/$exportId'
    | '/api/projects/$projectId'
    | '/api/share/$token'
    | '/api/projects/$projectId/assets'
    | '/api/projects/$projectId/book'
    | '/api/projects/$projectId/close'
    | '/api/projects/$projectId/duplicate'
    | '/api/projects/$projectId/export'
    | '/api/projects/$projectId/layouts'
    | '/api/projects/$projectId/publish'
    | '/api/projects/$projectId/layouts/$layoutId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/layout-parity'
    | '/api/health'
    | '/api/projects'
    | '/projects/$projectId'
    | '/s/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/projects'
    | '/api/assets/$assetId'
    | '/api/exports/$exportId'
    | '/api/projects/$projectId'
    | '/api/share/$token'
    | '/api/projects/$projectId/assets'
    | '/api/projects/$projectId/book'
    | '/api/projects/$projectId/close'
    | '/api/projects/$projectId/duplicate'
    | '/api/projects/$projectId/export'
    | '/api/projects/$projectId/layouts'
    | '/api/projects/$projectId/publish'
    | '/api/projects/$projectId/layouts/$layoutId'
  id:
    | '__root__'
    | '/'
    | '/layout-parity'
    | '/api/health'
    | '/api/projects'
    | '/projects/$projectId'
    | '/s/$token'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/projects/'
    | '/api/assets/$assetId'
    | '/api/exports/$exportId'
    | '/api/projects/$projectId'
    | '/api/share/$token'
    | '/api/projects/$projectId/assets'
    | '/api/projects/$projectId/book'
    | '/api/projects/$projectId/close'
    | '/api/projects/$projectId/duplicate'
    | '/api/projects/$projectId/export'
    | '/api/projects/$projectId/layouts'
    | '/api/projects/$projectId/publish'
    | '/api/projects/$projectId/layouts/$layoutId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutParityRoute: typeof LayoutParityRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  STokenRoute: typeof STokenRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiAssetsAssetIdRoute: typeof ApiAssetsAssetIdRoute
  ApiExportsExportIdRoute: typeof ApiExportsExportIdRoute
  ApiShareTokenRoute: typeof ApiShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout-parity': {
      id: '/layout-parity'
      path: '/layout-parity'
      fullPath: '/layout-parity'
      preLoaderRoute: typeof LayoutParityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$assetId': {
      id: '/api/assets/$assetId'
      path: '/api/assets/$assetId'
      fullPath: '/api/assets/$assetId'
      preLoaderRoute: typeof ApiAssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exports/$exportId': {
      id: '/api/exports/$exportId'
      path: '/api/exports/$exportId'
      fullPath: '/api/exports/$exportId'
      preLoaderRoute: typeof ApiExportsExportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId': {
      id: '/api/projects/$projectId'
      path: '/$projectId'
      fullPath: '/api/projects/$projectId'
      preLoaderRoute: typeof ApiProjectsProjectIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/share/$token': {
      id: '/api/share/$token'
      path: '/api/share/$token'
      fullPath: '/api/share/$token'
      preLoaderRoute: typeof ApiShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/assets': {
      id: '/api/projects/$projectId/assets'
      path: '/assets'
      fullPath: '/api/projects/$projectId/assets'
      preLoaderRoute: typeof ApiProjectsProjectIdAssetsRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/book': {
      id: '/api/projects/$projectId/book'
      path: '/book'
      fullPath: '/api/projects/$projectId/book'
      preLoaderRoute: typeof ApiProjectsProjectIdBookRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/close': {
      id: '/api/projects/$projectId/close'
      path: '/close'
      fullPath: '/api/projects/$projectId/close'
      preLoaderRoute: typeof ApiProjectsProjectIdCloseRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/duplicate': {
      id: '/api/projects/$projectId/duplicate'
      path: '/duplicate'
      fullPath: '/api/projects/$projectId/duplicate'
      preLoaderRoute: typeof ApiProjectsProjectIdDuplicateRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/export': {
      id: '/api/projects/$projectId/export'
      path: '/export'
      fullPath: '/api/projects/$projectId/export'
      preLoaderRoute: typeof ApiProjectsProjectIdExportRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/layouts': {
      id: '/api/projects/$projectId/layouts'
      path: '/layouts'
      fullPath: '/api/projects/$projectId/layouts'
      preLoaderRoute: typeof ApiProjectsProjectIdLayoutsRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/publish': {
      id: '/api/projects/$projectId/publish'
      path: '/publish'
      fullPath: '/api/projects/$projectId/publish'
      preLoaderRoute: typeof ApiProjectsProjectIdPublishRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/projects/$projectId/layouts/$layoutId': {
      id: '/api/projects/$projectId/layouts/$layoutId'
      path: '/$layoutId'
      fullPath: '/api/projects/$projectId/layouts/$layoutId'
      preLoaderRoute: typeof ApiProjectsProjectIdLayoutsLayoutIdRouteImport
      parentRoute: typeof ApiProjectsProjectIdLayoutsRoute
    }
  }
}

interface ApiProjectsProjectIdLayoutsRouteChildren {
  ApiProjectsProjectIdLayoutsLayoutIdRoute: typeof ApiProjectsProjectIdLayoutsLayoutIdRoute
}

const ApiProjectsProjectIdLayoutsRouteChildren: ApiProjectsProjectIdLayoutsRouteChildren =
  {
    ApiProjectsProjectIdLayoutsLayoutIdRoute:
      ApiProjectsProjectIdLayoutsLayoutIdRoute,
  }

const ApiProjectsProjectIdLayoutsRouteWithChildren =
  ApiProjectsProjectIdLayoutsRoute._addFileChildren(
    ApiProjectsProjectIdLayoutsRouteChildren,
  )

interface ApiProjectsProjectIdRouteChildren {
  ApiProjectsProjectIdAssetsRoute: typeof ApiProjectsProjectIdAssetsRoute
  ApiProjectsProjectIdBookRoute: typeof ApiProjectsProjectIdBookRoute
  ApiProjectsProjectIdCloseRoute: typeof ApiProjectsProjectIdCloseRoute
  ApiProjectsProjectIdDuplicateRoute: typeof ApiProjectsProjectIdDuplicateRoute
  ApiProjectsProjectIdExportRoute: typeof ApiProjectsProjectIdExportRoute
  ApiProjectsProjectIdLayoutsRoute: typeof ApiProjectsProjectIdLayoutsRouteWithChildren
  ApiProjectsProjectIdPublishRoute: typeof ApiProjectsProjectIdPublishRoute
}

const ApiProjectsProjectIdRouteChildren: ApiProjectsProjectIdRouteChildren = {
  ApiProjectsProjectIdAssetsRoute: ApiProjectsProjectIdAssetsRoute,
  ApiProjectsProjectIdBookRoute: ApiProjectsProjectIdBookRoute,
  ApiProjectsProjectIdCloseRoute: ApiProjectsProjectIdCloseRoute,
  ApiProjectsProjectIdDuplicateRoute: ApiProjectsProjectIdDuplicateRoute,
  ApiProjectsProjectIdExportRoute: ApiProjectsProjectIdExportRoute,
  ApiProjectsProjectIdLayoutsRoute:
    ApiProjectsProjectIdLayoutsRouteWithChildren,
  ApiProjectsProjectIdPublishRoute: ApiProjectsProjectIdPublishRoute,
}

const ApiProjectsProjectIdRouteWithChildren =
  ApiProjectsProjectIdRoute._addFileChildren(ApiProjectsProjectIdRouteChildren)

interface ApiProjectsRouteChildren {
  ApiProjectsProjectIdRoute: typeof ApiProjectsProjectIdRouteWithChildren
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsProjectIdRoute: ApiProjectsProjectIdRouteWithChildren,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutParityRoute: LayoutParityRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  STokenRoute: STokenRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiAssetsAssetIdRoute: ApiAssetsAssetIdRoute,
  ApiExportsExportIdRoute: ApiExportsExportIdRoute,
  ApiShareTokenRoute: ApiShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
